import type { Metadata } from 'next';
import { Badge, BriefcaseBusiness, Camera, Link2, MessageCircle, Newspaper, Users, X } from 'lucide-react';

export const metadata: Metadata = { title: 'Links' };

const logo = '/assets/Logo Marca Grupo MaisB/Logo Grupo Mais Barato (White Monoegativo).webp';

export default function LinksPage() {
  return <div className="page-container"><main className="links-card"><section className="card-top"><a className="card-close-btn" href="/" aria-label="Voltar ao site"><X size={20} /></a><div className="profile-logo logo-wrapper"><img src={logo} alt="Grupo Mais Barato" /></div><h1 className="profile-handle profile-name">GRUPO MAIS BARATO</h1><p className="profile-subtitle">Grupo Mais Barato • Supermercado • Farma • Gastronomia • Lazer</p><div className="social-row"><a href="https://www.instagram.com/maisbsupermercados" target="_blank" rel="noopener" className="social-icon-btn" aria-label="Instagram"><Camera size={19} /></a><a href="https://www.facebook.com" target="_blank" rel="noopener" className="social-icon-btn" aria-label="Facebook"><Users size={19} /></a><a href="https://www.linkedin.com" target="_blank" rel="noopener" className="social-icon-btn" aria-label="LinkedIn"><Badge size={19} /></a><a href="https://wa.me/5591984040710" target="_blank" rel="noopener" className="social-icon-btn" aria-label="WhatsApp"><MessageCircle size={19} /></a></div><a href="/" className="btn-link white-btn"><Link2 size={17} /> <span>Site Institucional Grupo Mais Barato</span></a><a href="/noticias" className="btn-link black-btn"><Newspaper size={17} /> <span>Notícias & Novidades do Grupo</span></a><a href="https://grupomaisbarato.portaldetalentos.senior.com.br/" target="_blank" rel="noopener" className="btn-link black-btn"><BriefcaseBusiness size={17} /> <span>Trabalhe Conosco</span></a><a href="https://wa.me/5591984040710" target="_blank" rel="noopener" className="btn-link black-btn"><MessageCircle size={17} /> <span>WhatsApp | Fale Conosco</span></a></section><section className="card-bottom"><h2>Marcas do Grupo</h2><div className="brands-list"><a className="brand-item" href="/#marca-super" aria-label="Supermercados +B"><span className="brand-logo-container"><img src="/assets/Icones Submarcas/icon-b-supermercadoo.png" alt="" /></span><span>+B Supermercados</span></a><a className="brand-item" href="/#marca-farma" aria-label="+B Farma"><span className="brand-logo-container"><img src="/assets/Icones Submarcas/icon-b-farmaa.png" alt="" /></span><span>+B Farma</span></a><a className="brand-item" href="/#marca-wine" aria-label="The Wine Experience"><span className="brand-logo-container"><img src="/assets/Icones Submarcas/icon-the-winee.png" alt="" /></span><span>The Wine Experience</span></a><a className="brand-item" href="/#marca-plaza" aria-label="Villa Plaza"><span className="brand-logo-container"><img src="/assets/Icones Submarcas/icon-vila-plaza.png" alt="" /></span><span>Villa Plaza</span></a><a className="brand-item" href="/#marca-park" aria-label="Villa Plaza Park"><span className="brand-logo-container"><img src="/assets/Icones Submarcas/icon-vila-plaza.png" alt="" /></span><span>Villa Plaza Park</span></a></div></section></main></div>;
}
